# Generated by Django 5.2.15 on 2026-06-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_date_of_birth_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patient_id',
            field=models.CharField(blank=True, help_text='Unique patient registration number (auto-generated)', max_length=12, null=True, unique=True),
        ),
    ]
