# Generated by Django 5.2.15 on 2026-06-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo (optional)', null=True, upload_to='profile_photos/%Y/%m/'),
        ),
    ]
