# Generated by Django 6.0.6 on 2026-06-19 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, help_text='Receive notifications via email')),
                ('sms_enabled', models.BooleanField(default=True, help_text='Receive notifications via SMS')),
                ('appointment_reminders', models.BooleanField(default=True, help_text='Receive appointment reminders')),
                ('queue_notifications', models.BooleanField(default=True, help_text='Receive queue turn notifications')),
                ('lab_results', models.BooleanField(default=True, help_text='Receive lab result notifications')),
                ('follow_up_reminders', models.BooleanField(default=True, help_text='Receive follow-up reminders')),
                ('payment_notifications', models.BooleanField(default=True, help_text='Receive payment notifications')),
                ('general_notifications', models.BooleanField(default=True, help_text='Receive general notifications')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'ordering': ['-updated_at'],
            },
        ),
    ]
