# Generated by Django 5.2.15 on 2026-06-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_doctorreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jazzcash_number', models.CharField(blank=True, help_text='JazzCash mobile account number (e.g., 0300-1234567)', max_length=20, null=True)),
                ('easypaisa_number', models.CharField(blank=True, help_text='EasyPaisa mobile account number (e.g., 0311-7654321)', max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name (e.g., HBL, UBL, Meezan Bank)', max_length=100, null=True)),
                ('bank_account_title', models.CharField(blank=True, help_text='Bank account title', max_length=200, null=True)),
                ('bank_account_number', models.CharField(blank=True, help_text='Bank account number / IBAN', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
