# Generated by Django 5.2.15 on 2026-06-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_paymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='e.g., 120/80', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='pulse',
            field=models.CharField(blank=True, help_text='e.g., 72 bpm', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='symptoms',
            field=models.TextField(blank=True, help_text="Patient's reported symptoms"),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='temperature',
            field=models.CharField(blank=True, help_text='e.g., 98.6 F', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g., 70 kg', max_length=10, null=True),
        ),
    ]
