# Generated by Django 5.2.15 on 2026-06-06 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_patienthistory_blood_pressure_patienthistory_pulse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='lab_reports',
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='lab_tests_ordered',
            field=models.TextField(blank=True, help_text='Lab tests ordered (e.g., CBC, Blood Sugar, X-Ray)'),
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='e.g., CBC, Blood Sugar, X-Ray, Ultrasound', max_length=200)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('IN_LAB', 'In Lab'), ('RESULTS_RECEIVED', 'Results Received'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=20)),
                ('results', models.TextField(blank=True, help_text='Lab test results / findings')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='lab_reports/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('ordered_date', models.DateField(auto_now_add=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_ordered', to=settings.AUTH_USER_MODEL)),
                ('history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='clinic.patienthistory')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ordered_date'],
            },
        ),
    ]
