# Generated by Django 5.2.15 on 2026-06-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_remove_patienthistory_lab_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='previous_records',
            field=models.FileField(blank=True, help_text='Upload previous doctor prescriptions, reports, or medical documents', null=True, upload_to='previous_records/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='previous_records_notes',
            field=models.TextField(blank=True, help_text='Notes about previous medical records (doctor name, hospital, date)'),
        ),
    ]
