# Generated by Django 5.2.15 on 2026-06-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_patienthistory_previous_records_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(help_text='e.g., Blood Test, Radiology, Urine Test, Microbiology', max_length=100)),
                ('default_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Default cost in PKR', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lab Test Category',
                'verbose_name_plural': 'Lab Test Categories',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of this lab test in PKR', max_digits=10),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_category',
            field=models.CharField(blank=True, help_text='e.g., Blood Test, Radiology, Urine Test', max_length=100, null=True),
        ),
    ]
